pipeline:
  build-app:
    image: node:latest
    environment:
      - APP_NAME=sun-forever-tw_pv_monitoring_system_web_app
      - DOCKER_USERNAME=sunforevertw
    commands:
      - chmod +x .scripts/install-meteor.sh && .scripts/install-meteor.sh
      - cd ./app && meteor build ../build --architecture os.linux.x86_64
      - cd ../build && tar -zxvf app.tar.gz
      - ls
      # - cd ../ && docker build -t $${DOCKER_USERNAME}/$${APP_NAME}:${DRONE_TAG} .
