pipeline:
  build-app:
    image: node:latest
    environment:
      - APP_NAME=drone_test_meteor
      - DOCKER_USERNAME=sunforevertw
    commands:
      - ls
      - export APP_SOURCE_DIR="$${CI_WORKSPACE}"/app
      - echo $APP_SOURCE_DIR
      # - printenv
      - chmod +x .scripts/install-meteor.sh && .scripts/install-meteor.sh
      - ls ~
      - cd $APP_SOURCE_DIR
      - ls
      - meteor build ../build --architecture os.linux.x86_64 --allow-superuser
      - cd ../build && tar -zxvf app.tar.gz
      - echo "${DOCKER_USERNAME}/${APP_NAME}":${DRONE_TAG}
      - cd ../ && docker build -t "${DOCKER_USERNAME}"/"${APP_NAME}":${DRONE_TAG} .

    # rebuild-cache:
    #   image: drillster/drone-volume-cache
    #   rebuild: false
    #   mount:
    #     - ~/.meteor
    #   volumes:
    #     - /volume1/docker/drone/var/lib/drone/cache:/var/lib/drone/cache
